### ISSUE TITLE
Using official ovpn provided files have problem when getSignature : `unable to get local issuer certificate`

### ISSUE THREAD

**Issue by StudioEtrange** [pia-foss/manual-connections#92] opened 2021-01-31 02:47 UTC
I use get_token.sh, and port_forwarding.sh, with all env var correctly setted
and a problem occurs when getting new signature in port_fowarding.sh

Error message is : `unable to get local issuer certificate`

 I use the ovpn files you provided here : https://www.privateinternetaccess.com/helpdesk/kb/articles/where-can-i-find-your-ovpn-files

```

curl -v -m 5     --connect-to "$PF_HOSTNAME::$PF_GATEWAY:"     --cacert "/whatever/manual-connections/ca.rsa.4096.crt"     -G --data-urlencode "token=${PIA_TOKEN}"     "https://${PF_HOSTNAME}:19999/getSignature"
* Connecting to hostname: 10.13.112.1
*   Trying 10.13.112.1:19999...
* Connected to 10.13.112.1 (10.13.112.1) port 19999 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /whatever/manual-connections/ca.rsa.4096.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Real values are : 
```curl -v -m 5 --connect-to de-berlin.privacy.network::10.13.112.1: --cacert /whatever/manual-connections/ca.rsa.4096.crt -G --data-urlencode token=***** https://de-berlin.privacy.network:19999/getSignature```

I have also tried with server from switzerland

The only solution I get for now, which is not a good thing, is to bypass certificate check by editing your scripts and add `-k` to curl in `port_forwarding.sh`
With this modificaton everything works smoothly, I obtain a port from port_forwarding.sh !

**Comment by g00nix** [comment] 2021-01-31 10:38
@StudioEtrange please check if this ticket is a duplicate of https://github.com/pia-foss/manual-connections/issues/85

**Comment by g00nix** [comment] 2021-01-31 17:31
@StudioEtrange The certificates in this repo are the same as the ones in the config files downloaded from the website.
You need the certificates only for the OpenVPN connection, but you have flexibility when connecting to the PIA PF. The PIA PF supports both the PIA CA, as also the normal CAs which are available on all distributions. [Here](https://archlinux.org/packages/core/any/ca-certificates/) is an example of a package that should be installed by default on every system.

This mean you can use any certificate with the PF API. The error message you are getting from your HTTPS client (curl) indicates that you asked `curl` to accept a certificate signed by the PIA CA but at the same time requested the regional Let's Encrypt certificate from the HTTPS server. This is how curl works, and also how web servers work. They check the SNI and after that send the appropriate certificate to establish a HTTPS connection. 

The self signed CA provides better security. The regional certificate allows you to get from DNS the best servers per region and also to connect without specifying a CA (since your operating system will probably already have the Root CA from Let's Encrypt). Just pick one.

**Comment by g00nix** [comment] 2021-02-02 09:26
Closing as a duplicate of https://github.com/pia-foss/manual-connections/issues/85

**Closed by g00nix** 2021-02-02 09:26 UTC
