### ISSUE TITLE
OpenVPN issues with Next-Gen using the manual connection method

### ISSUE THREAD

**Issue by binhex** [pia-foss/manual-connections#7] opened 2020-09-28 08:20 UTC
So i have opened a ticket with PIA support regards this, but i thought it worth posting on here as a heads up to anybody else seeing issues getting a incoming port assigned using OpenVPN:-

So i have used the manual connection method detailed in this repo for OpenVPN to get a incoming port assigned, however this does not work as intended (most of the time). 

When getting to the stage where we are making a request to get the payload and signature, i am seeing more often than not a json reply back from the server that the 'Login Failed', now obviously at this point i already have a connection to you, so i know the authentication is sound, and if i put in retries to my code then it will eventually authenticate and issue a incoming port, so i am confident my code is correct.

FYI this is the reply i got back from PIA Support regards this issue (ticket raised):-
```
Thank you for reaching us here at PIA Customer Support.

I understand that you are having issues when setting up manual port forwarding. **This is a known issue and our DevOps team are aware and currently working in resolving this matter.**

It is currently in Alpha stage, but they've made a tremendous progress and plan to update the script(s).

We appreciate your patience on this matter.
```

**Comment by g00nix** [comment] 2020-09-28 12:43
In order to set up OpenVPN with NextGen, please head over to https://www.privateinternetaccess.com/pages/download and click on _View OpenVPN Configurations_. In case you also want to enable [port forwarding](https://github.com/pia-foss/manual-connections/blob/master/port_forwarding.sh), please be sure you are connected to a region that supports port forwarding. 

We are working on providing OpenVPN support for this repository, including support for PF on top of OpenVPN. This will probably be part of version **v0.2.0**.

**Comment by binhex** [comment] 2020-09-28 13:46
> In order to set up OpenVPN with NextGen, please head over to https://www.privateinternetaccess.com/pages/download and click on _View OpenVPN Configurations_. In case you also want to enable [port forwarding](https://github.com/pia-foss/manual-connections/blob/master/port_forwarding.sh), please be sure you are connected to a region that supports port forwarding.

ive already done this, i am using a openvpn config file for next-gen with a location that supports port forwarding.

> We are working on providing OpenVPN support for this repository, including support for PF on top of OpenVPN. This will probably be part of version **v0.2.0**.

im a little confused by this, surely getting an incoming port assigned should not be dependent on whether you use wireguard of openvpn?, a port is a port, right? are you saying the current manual connection method doesn't work with openvpn in some way?.

**Comment by fcastilloec** [comment] 2020-09-28 17:30
@binhex I agree that getting a port should be protocol independent. I had my scripts based on [this code](https://github.com/fm407/PIA-NextGen-PortForwarding/blob/master/pia-nextgen-pf.sh). Specifically, I'm using https://www.privateinternetaccess.com/api/client/v2/token to retrieve a token, which I save into a file and reuse it. And for the port, I use `traceroute` (L#72 in the code) to bind/retrieve the port.
So, the IP address might be different for `wg` from `OpenVPN` and that's why it might not be working for you.

**Comment by g00nix** [comment] 2020-09-28 19:27
## The manual way

> Specifically, I'm using https://www.privateinternetaccess.com/api/client/v2/token to retrieve a token, which I save into a file and reuse it.

Please use the new v3 client authentication. The code you are linking is running AFTER the connection got established, so you can get a token via:
```bash
curl -ks -u "$PIA_USER:$PIA_PASS" \
    https://10.0.0.1/authv3/generateToken
```
The new `authv3` system is currently available via Meta IPs (before connecting to the VPN) and via `10.0.0.1` (after connecting to the VPN). This will also be available with a stable URL as soon as it is ready.

To access the PF API with any protocol, you need to get your gateway. An easy way to find your gateway on OpenVPN is: `ip route | head -1 | grep tun | awk '{ print $3 }'`.

So you can reach getSignature with something like this  (I did not test this exact bit of code):
```bash
curl -ks -m 5 \
    -G --data-urlencode "token=${PIA_TOKEN}" \
    "https://$(ip route | head -1 | grep tun | awk '{ print $3 }'):19999/getSignature
```

## The easier way

However you don't really need to write your own script for PF cause you can just use [port_forwarding.sh](https://github.com/pia-foss/manual-connections/blob/master/port_forwarding.sh). First use [get_region_and_token.sh](https://github.com/pia-foss/manual-connections/blob/master/get_region_and_token.sh) to get the hostname, the IP you want to connect to and your v3 VPN token. After that, manually establish a VPN connection to NextGen according to the manual connection setup.

After having a connection, you can just start the PF script with the information you already have:
```bash
PF_GATEWAY=$(ip route | head -1 | grep tun | awk '{ print $3 }') \
  PF_HOSTNAME=yourServer (the one you got from get_region_and_token.sh) \
  PIA_TOKEN=yourToken (the one you got from get_region_and_token.sh) \
  ./port_forwarding.sh
```

What we currently have on our roadmap is to provide an OpenVPN scripts that can be used instead of [the wireguard script](https://github.com/pia-foss/manual-connections/blob/master/connect_to_wireguard_with_token.sh) to connect to a VPN server and is also able to start [the PF script](https://github.com/pia-foss/manual-connections/blob/master/port_forwarding.sh) after that. We also need to properly test it internally before releasing it to master, however I will post here (on this issue) as soon as the code is available on a separate branch.

If this is super urgent and you still have troubles getting PF working with OpenVPN and you can not wait till we officially finish the script, please contact me on freenode and I'll help you through this. My nick is gunix and I can be found on #privateinternetaccess

**Comment by binhex** [comment] 2020-09-28 20:11
i have studied all your scripts in this repo and i am using a combinaiton of methods detailed in your scripts get a incoming port assigned, and yes **it DOES work**, but its fails more often than not, causing multiple retries before i finally get a port assigned. im not going to drop the whole of my script in here as it has a lot of retry togic and debugging in there, but in short i am doing the following steps, let me know if im missing any steps:-

```
# download json data
jq_query_result=$(curl --interface "${VPN_DEVICE_TYPE}" -s --insecure "${pia_vpninfo_api}")

# get metadata server ip address
vpn_remote_metadata_server_ip=$(echo "${jq_query_result}" | jq -r "${jq_query_metadata_ip}")

# get token json response
token_json_response=$(curl --interface "${VPN_DEVICE_TYPE}" -s --insecure -u "${VPN_USER}:${VPN_PASS}" "https://${vpn_remote_metadata_server_ip}/authv3/generateToken")

# get token
token=$(echo "${token_json_response}" | jq -r '.token')

# get payload and signature
payload_and_sig=$(curl --interface "${VPN_DEVICE_TYPE}" -s --insecure "https://${vpn_gateway_ip}:19999/getSignature?token=${token}")

payload=$(echo "${payload_and_sig}" | jq -r '.payload')
signature=$(echo "${payload_and_sig}" | jq -r '.signature')

# decode payload to get token, port, and expires date (2 months)
payload_decoded=$(echo "${payload}" | base64 -d | jq)
token=$(echo "${payload_decoded}" | jq -r '.token')
port=$(echo "${payload_decoded}" | jq -r '.port')

# note expires_at time in this format'2020-11-24T22:12:07.627551124Z'
expires_at=$(echo "${payload_decoded}" | jq -r '.expires_at')

# bind poort assigned
bind_port=$(curl -sGk --data-urlencode "payload=${payload}" --data-urlencode "signature=${signature}" "https://${vpn_gateway_ip}:19999/bindPort")
```

It fails more often than not at the step where it attempts to download the payload, if i look at the json returned it states ' Login Failed' which of course is not due to incorrect credentials, as i already have a vpn connection at that point, any clues as to why im getting this issue with downloading the payload?

**Comment by fcastilloec** [comment] 2020-09-28 20:16
@g00nix Thanks so much for the extra info, especially the use of `10.0.0.1`.

I still write my own scripts because I don't like running undefined while loops for multiple reasons.
I personally prefer a cron job instead. So my script just sets a cron job that runs a binding script, and when I disconnect, the cron job gets deleted. Besides that modification, everything is pretty much the same.

**Comment by g00nix** [comment] 2020-09-28 21:12
### @binhex

the fact it's failing intermittently is confusing. This would normally indicate server issues, but we've been testing this new PF API for months now and we didn't reproduce this issue. I understand you don't want to actually post everything here, but I think it would be easier if you would actually post your code on your git page so that I can have a look, maybe I find the bug.

I can also start shooting in the dark with questions like:
1. how do you get your `vpn_gateway_ip`?
2. are you sure OpenVPN connects before moving forward with the rest of the script?
3. why are you trying to curl with `--interface`? That shouldn't be required, it should work only with the gateway IP.

I also do not see how this bit here fits with the rest of the script:
```
vpn_remote_metadata_server_ip=$(echo "${jq_query_result}" | jq -r "${jq_query_metadata_ip}")
```

### @fcastilloec 

> I personally prefer a cron job instead.

I am super happy you got that working for you :+1: 
That's why the scripts have all of the comments, so that you get a full picture of what is happening so that you can modify them any way you want.

**Comment by binhex** [comment] 2020-09-28 22:21
hi @g00nix , thanks for the replies, i think i figured out what the issue is!, i suspect its the way i was passing in the token, i wasnt using urlencode and i THINK because the token is randomly generated i would sometimes get lucky with the token and the api would not have any issues with the string, but other times it would contain characters which, if not url encoded, would cause issues and thus trigger the login failure.

this was my original code:-
```
payload_and_sig=$(curl --interface "${VPN_DEVICE_TYPE}" -s --insecure "https://${vpn_gateway_ip}:19999/getSignature?token=${token}")
```
and looking at your example, i then modified it to be:-
```
payload_and_sig=$(curl --insecure --silent --max-time 5 --get --data-urlencode "token=${token}" "https://${vpn_gateway_ip}:19999/getSignature")
```
and that has been a LOT more stable, no failures yet but i would like to keep this issue open for a few days if thats ok, if its still ok after that i will close the issue.

**Comment by binhex** [comment] 2020-09-29 08:52
A small edition to the above, everything is still working great now!, you might want to consider changing the PIA Technical Article, as this is where i got the idea to use the token as a parameter in the URL without any URL Encoding, which as i have now found out, doesn't work as expected causing Login Failures, excerpt from the Article:-

```
Example:

bash-5.0# curl -k "https://10.4.128.1:19999/getSignature?token=$TOKEN"
{
    "status": "OK",
    "payload": "eyJ0b2tlbiI6Inh4eHh4eHh4eCIsInBvcnQiOjQ3MDQ3LCJjcmVhdGVkX2F0IjoiMjAyMC0wNC0zMFQyMjozMzo0NC4xMTQzNjk5MDZaIn0=",
    "signature": "a40Tf4OrVECzEpi5kkr1x5vR0DEimjCYJU9QwREDpLM+cdaJMBUcwFoemSuJlxjksncsrvIgRdZc0te4BUL6BA=="
} 
```

Link to the Technical Article:- https://www.privateinternetaccess.com/helpdesk/kb/articles/next-generation-port-forwarding

**Comment by g00nix** [comment] 2020-09-29 12:14
@binhex thank you for finding the bug within the documentation on the website!

The ticket should however stay opened until we publish the scripts for OpenVPN

**Comment by binhex** [comment] 2020-09-29 12:19
@g00nix ok no probs, TBH i am not after a fully fleshed out OpenVPN script, i prefer to roll my own, and i now have everything i require, but i will leave this issue open as requested.

Many thanks for your help!.

**Comment by fcastilloec** [comment] 2020-10-02 04:31
@g00nix you mention a way to get the gateway for OpenVPN, is there a similar way to get the gateway when connected through wireguard? I know that running `curl` to `https://${WG_HOSTNAME}:1337/addKey` can give you `server_vip` which is the gateway, but is there a different way to get that IP? The problem is that the previous call requires the private and public keys, which are not saved. Does this gateway IP changes often? Or can I hardcode that IP for future calls to the same server?

PS: Sorry for asking in this thread. If preferred, I'll open a new issue for this question.

**Comment by g00nix** [comment] 2020-10-02 08:52
This indeed has nothing to do with the OpenVPN issue. please open another ticket.

**Comment by SideSwipe9th** [comment] 2020-10-03 16:52
@g00nix I just completed updating my scripts using the information that you and @binhex have discussed over the last few days. I've got to the stage where I'm able to successfully request a token, signature, payload, and port bind from the next generation authentication servers as all of the requests return success messages. And I'm able to feed the info from the script requesting the port into those that update my firewall and Transmisson's settings. 

However whenever I try to use or test the port I've bound, either through Transmission or one of the many websites which can tell if a port is open or not, the request fails as it believes the port is closed. 

Scripting wise mine are pretty similar to those in this repository and those written by binhex. I'm not entirely sure what is happening as aside from Transmission and the external services saying the port is closed, everything in the request chain is returning a success message. I realise you guys are busy with the roll out of the new servers, do you have an ETA on when the official scripts will be available? Or can you suggest anything I should look at in further detail as to why my own scripts are apparently failing with a success message?

**Comment by g00nix** [comment] 2020-10-03 17:15
>  realise you guys are busy with the roll out of the new servers, do you have an ETA on when the official scripts will be available?

Probably tonight. We have a working script. There still are some small bugs and we need to merge the last diffs from master and push it to a new branch (will be flagged as `experimental`).

**Comment by SideSwipe9th** [comment] 2020-10-03 17:18
Cheers. Hopefully there's something in your scripts that I've missed in mine.

I'm now fairly certain the issue is not on my end. I thought it might be the software firewall on my machine blocking it, but I tried with it temporarily disabled and the issue still happened.

**Comment by g00nix** [comment] 2020-10-03 17:57
@SideSwipe9th how are you testing the port? Did you try testing with [tcpdump](https://github.com/pia-foss/manual-connections#testing-your-new-pf)?

**Comment by SideSwipe9th** [comment] 2020-10-03 18:26
I've just tested with tcpdump combined with the site that Transmission uses to determine if the port is open. I can see the request from Transmission's webserver come in: 

```
listening on tun0, link-type RAW (Raw IP), capture size 262144 bytes
18:14:55.284607 IP vm4.transmissionbt.com.53702 > <computer_name>.<port_number>: Flags [S], seq 3730990411, win 29200, options [mss 1352,sackOK,TS val 1140964980 ecr 0,nop,wscale 7], length 0
18:14:56.280688 IP vm4.transmissionbt.com.53702 > <computer_name>.<port_number>: Flags [S], seq 3730990411, win 29200, options [mss 1352,sackOK,TS val 1140965230 ecr 0,nop,wscale 7], length 0
18:14:58.284893 IP vm4.transmissionbt.com.53702 > <computer_name>.<port_number>: Flags [S], seq 3730990411, win 29200, options [mss 1352,sackOK,TS val 1140965731 ecr 0,nop,wscale 7], length 0
```

However the service itself returns a failed to connect status. Likewise if I test with another website like You Get Signal, I can see the requests coming in on tcpdump, but the website says the port is closed. System firewall wise, the machine is using iptables, for which I have three input rules specified for tun0; accept established, accept tcp on port forwarded by PIA, and reject everything else with icmp-port-unreachable. I tried testing earlier without the last of those rules, but with the same result.

**Comment by SideSwipe9th** [comment] 2020-10-03 18:36
Ok, further testing. I have nuked the iptables rules, and set it up to accept everything on tun0 and enp0s10 (the default wired connection). Again I can see the testing sites making attempts on tcpdump per the snippet in my last reply, but they all show the port that I've been forwarded by the API as closed.

**Comment by g00nix** [comment] 2020-10-03 18:48
> Ok, further testing. I have nuked the iptables rules, and set it up to accept everything on tun0 and enp0s10 (the default wired connection). Again I can see the testing sites making attempts on tcpdump per the snippet in my last reply, but they all show the port that I've been forwarded by the API as closed.

The port will still appear as closed if there is no service running on it. The fact you see the incoming traffic with tcpdump means that PF is working on the VPN server. Try to get some `nginx` (or similar) to listen on that port and the port should appear as opened.

**Comment by g00nix** [comment] 2020-10-03 18:53
The code for OpenVPN has been written and is currently sitting on a testing branch here: https://github.com/pia-foss/manual-connections/tree/testing_openvpn

This branch will get merged into master after the branch has been properly tested.

**Closed by g00nix** 2020-10-03 18:53 UTC

**Comment by SideSwipe9th** [comment] 2020-10-03 18:59
I've had Transmission listening on that port the whole time I've been testing. As I said in my original post my scripts, after requesting the port from the PIA API, update iptables, and Transmission accordingly. As far as I can tell, everything on my set up is correct right now. Transmission is listening on the PIA supplied port and on the correct interface, iptables is set to accept incoming connections on that port. 

I'll take a look at the testing branch now to see if there's any steps I missed when requesting the ticket, payload, port number, and binding.

**Comment by g00nix** [comment] 2020-10-03 19:03
@SideSwipe9th if you need some help at troubleshooting this, I can be reached on IRC on freenode on #privateinternetaccess
My nick is `gunix`

**Comment by g00nix** [comment] 2020-10-03 19:50
As a general idea about freenode, totally unrelated to this issue, if anybody needs to paste something to IRC, the proper way to do that is to use https://bpa.st/ or http://ix.io/ or similar services.
Sending lots of messages on freenode might result in a ban on the IP.
