### ISSUE TITLE
Can wireguard autoconnect like the desktop app?

### ISSUE THREAD

**Issue by bassamanator** [pia-foss/manual-connections#71] opened 2020-12-27 09:53 UTC
I'm connecting to PIA via wireguard successfully on my Raspberry Pi and Ubuntu system but I have to connect manually. I would like to connect to PIA automatically upon reboot.

Can this be done?

Thanks!

**Comment by g00nix** [comment] 2020-12-27 11:38
Yes, you can start the scripts on boot. The way to proceed depends on the init system you are using. Raspberry Pi has a documentation on systemd here: https://www.raspberrypi.org/documentation/linux/usage/systemd.md
Systemd works the same on Ubuntu and on all other distributions that implement it. This is a very good documentation on systemd: https://wiki.archlinux.org/index.php/Systemd

As distributions pick different systems for init, it becomes out of the scope of this repository to make these scripts run on boot. Though systemd is very popular, there are lots of distributions that choose something else.

Closing this ticket as a duplicate of https://github.com/pia-foss/manual-connections/issues/48

**Closed by g00nix** 2020-12-27 11:38 UTC
