### ISSUE TITLE
Make wireguard script ignore SSH traffic

### ISSUE THREAD

**Issue by stickz** [pia-foss/manual-connections#68] opened 2020-12-13 07:10 UTC
I would like to know if the wireguard script could be improved to allow SSH traffic to pass through the default network interface. Every time I try to test this script out on my dedicated server, it locks me out of the hosting.

**Comment by g00nix** [comment] 2020-12-13 18:26
Yes, this can be done, however this is out of the scope of this repository. The documentation on `wg-quick` can be found here: https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8

To manually adapt the script for this behavior, a change should be possible here: https://github.com/pia-foss/manual-connections/blob/v1.1.0/connect_to_wireguard_with_token.sh#L121-L129

Closing this ticket as duplicate of https://github.com/pia-foss/manual-connections/issues/62

**Closed by g00nix** 2020-12-13 18:26 UTC

**Comment by stickz** [comment] 2020-12-14 13:15
I have modified the script, but every time I bind a service to the VPN IP address, it fails to connect to the internet.

```
echo "
[Interface]
Address = $(echo "$wireguard_json" | jq -r '.peer_ip')
PrivateKey = $privKey
DNS= 1.1.1.1
[Peer]
PersistentKeepalive = 25
PublicKey = $(echo "$wireguard_json" | jq -r '.server_key')
AllowedIPs = $(echo "$wireguard_json" | jq -r '.peer_ip')/32
Endpoint = ${WG_SERVER_IP}:$(echo "$wireguard_json" | jq -r '.server_port')
" > /etc/wireguard/pia.conf || exit 1
echo OK!
```

**Comment by g00nix** [comment] 2020-12-14 13:52
Can you please create a github fork with your differences so that I can see the comparison with the git tools?

**Comment by stickz** [comment] 2020-12-14 13:55
Done. https://github.com/stickz/manual-connections/blob/master/connect_to_wireguard_with_token.sh

**Comment by g00nix** [comment] 2020-12-14 14:07
You need to add to AllowedIPs the networks that you want to send through the tunnel. Adding a `/32` will not work, as that is only one IP (the virtual IP address you received from the API on the VPN node). I suggest you study [subnetting](https://en.wikipedia.org/wiki/Subnetwork) before moving forward.

A common solution is to include all public network in AllowedIPs and not adding local networks. This will work if you want to SSH on the local network (if you do not have a public IP).

**Comment by stickz** [comment] 2020-12-14 21:48
Thanks for this information. I have modified my wireguard script to re-route SSH traffic through my public ip address and all other traffic through wireguard. However, when I connect to PIA via wireguard, I have no internet access.

I successfully set the three following 3 parameters before running the script.
```
echo "2 ssh" >> /etc/iproute2/rt_tables
net.ipv4.conf.all.rp_filter = 2
net.ipv4.ip_forward = 1
```

And changed the following lines in `connect_to_wireguard_with_token.sh`.
https://github.com/stickz/manual-connections/blob/master/connect_to_wireguard_with_token.sh#L121-L146

After the script completes, my pia wiregaurd network interface is successfully created. And it says I should have internet access.
```
pia: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
        inet 10.29.128.196  netmask 255.255.255.255  destination 10.29.128.196
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 1  bytes 92 (92.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 128  bytes 116352 (116.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
